#!/usr/bin/env bash
# 同梱する依存パッケージのライセンス文・NOTICEをまとめた THIRD_PARTY_LICENSES.txt を生成する
#
# 使い方:
#   scripts/gen-third-party-licenses.sh            リポジトリ直下の THIRD_PARTY_LICENSES.txt を更新
#   scripts/gen-third-party-licenses.sh <出力先>    指定パスに書き出す（release.sh の差分チェック用）
#
# 入力: Package.resolved（パッケージ名・バージョン・URL）と .build/checkouts/<name>/ の LICENSE*・NOTICE*
# 前提: swift package resolve 済みで、checkouts のリビジョンが Package.resolved と一致していること
# 依存を追加・更新したら、このスクリプトを実行して生成結果をコミットすること
set -euo pipefail

PROJ="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$PROJ/THIRD_PARTY_LICENSES.txt}"
RESOLVED="$PROJ/Package.resolved"
CHECKOUTS="$PROJ/.build/checkouts"
die() { echo "エラー: $*" >&2; exit 1; }

[[ -f "$RESOLVED" ]] || die "Package.resolved がありません"
[[ -d "$CHECKOUTS" ]] || die ".build/checkouts がありません（swift package resolve を実行してください）"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "PhotoMCP - Third-Party Licenses"
  echo "==============================="
  echo
  echo "PhotoMCP includes the following third-party software."
  echo "Each component is distributed under its own license, reproduced below."
  echo "(This file is generated by scripts/gen-third-party-licenses.sh. Do not edit by hand.)"

  jq -r '.pins | sort_by(.identity) | .[] | [.identity, .location, (.state.version // "-"), .state.revision] | @tsv' "$RESOLVED" |
  while IFS=$'\t' read -r name url version revision; do
    dir="$CHECKOUTS/$name"
    [[ -d "$dir" ]] || die "checkout がありません: $dir"
    actual="$(git -C "$dir" rev-parse HEAD)"
    [[ "$actual" == "$revision" ]] || die "$name のリビジョンが Package.resolved と一致しません（$actual != $revision）。swift package resolve を実行してください"

    echo
    echo
    echo "################################################################################"
    echo "# $name $version"
    echo "# $url"
    echo "################################################################################"

    found=0
    for f in $(cd "$dir" && ls | grep -iE '^(license|licence|copying|notice)([.-].*)?$' | sort); do
      found=1
      echo
      echo "---- $f ----"
      echo
      cat "$dir/$f"
    done
    [[ $found -eq 1 ]] || die "$name にライセンスファイルが見つかりません"
  done
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "生成: $OUT"
